# file-operations schema v2.0.0

name: file-operations
version: "2.0.0"
description: "Safe filesystem operations with path protection, backup enforcement, and audit logging"
type: agent
category: system

risk_level: medium
consensus_level: adaptive
trust: supervised
parallel_safe: false
tools: [Read, Write, Edit, Glob, Grep, Bash]

# ─────────────────────────────────────────────
# Routing
# ─────────────────────────────────────────────
routing:
  use_when:
    - "Filesystem operations needing safety controls (backup, validation, audit)"
    - "Operations on files near protected system paths"
    - "Batch operations requiring atomic rollback"
    - "Operations needing structured output (success/failure, backup paths, byte counts)"
  do_not_use_when:
    - condition: "Single file read with known path"
      instead: "Read tool directly"
      reason: "Skill overhead unnecessary for deterministic single-step read"
    - condition: "Content search by pattern"
      instead: "Grep tool directly"
      reason: "Grep is faster and more targeted"
    - condition: "File search by name"
      instead: "Glob tool directly"
      reason: "Glob handles pattern matching natively"
    - condition: "Writing a single new file with known content"
      instead: "Write tool directly"
      reason: "No backup or validation needed for new files"

# ─────────────────────────────────────────────
# Inputs — Skill-level contract
# ─────────────────────────────────────────────
inputs:
  operation:
    type: string
    required: true
    enum: [read_file, create_file, update_file, delete_file, delete_directory, move_file, copy_file, search_files, set_permissions]
    description: The filesystem operation to perform

  path:
    type: string
    required: true
    description: Absolute path to the target file or directory
    validation:
      - "MUST be an absolute path (starts with /)"
      - "MUST NOT match any protected_paths entry"

  content:
    type: string
    required: false
    description: File content (for create/update operations)

  destination:
    type: string
    required: false
    description: Destination path (for move/copy operations)

  pattern:
    type: string
    required: false
    description: Search pattern (for search) or match pattern (for replace)

  create_backup:
    type: boolean
    required: false
    default: true
    description: Whether to create a backup before destructive operations

  permissions:
    type: string
    required: false
    description: File permissions in octal (e.g., "644")
    validation:
      - "MUST NOT be '777' when recursive is true"

  recursive:
    type: boolean
    required: false
    default: false
    description: Whether to operate recursively on directories

  intent:
    type: string
    required: true
    description: >
      One-sentence explanation of WHY this operation is being performed.
      Makes logs auditable and reduces hallucinated invocations.

# ─────────────────────────────────────────────
# Outputs — Skill-level contract
# ─────────────────────────────────────────────
outputs:
  success:
    type: boolean
    description: Whether the operation completed successfully

  path:
    type: string
    description: The absolute path that was operated on

  content:
    type: string
    description: File content (for read operations)

  bytes_read:
    type: integer
    description: Number of bytes read (for read operations)

  bytes_written:
    type: integer
    description: Number of bytes written (for create/update operations)

  bytes_copied:
    type: integer
    description: Number of bytes copied (for copy operations)

  backup_path:
    type: string
    description: Path to backup file if one was created

  previous_permissions:
    type: string
    description: Permissions before change (for set_permissions)

  matches:
    type: array
    items:
      type: string
    description: List of matching file paths (for search operations)

  match_count:
    type: integer
    description: Number of search results

  files_deleted:
    type: integer
    description: Count of files removed (for delete_directory)

  error:
    type: string
    description: Error message if operation failed

# ─────────────────────────────────────────────
# Capabilities — Per-operation definitions
# ─────────────────────────────────────────────
capabilities:
  - name: read_file
    description: >
      Read file contents with encoding support.
      Use when checking file contents, analyzing logs, or reading configuration.
      Do NOT use for binary files larger than 100MB.
    risk: low
    consensus: any
    parallel_safe: true
    intent_required: true
    inputs:
      path:
        type: string
        required: true
      encoding:
        type: string
        required: false
        enum: [utf-8, ascii, binary]
        default: utf-8
      lines:
        type: string
        required: false
        description: "Line range (e.g., '1-50')"
    outputs:
      content:
        type: string
      bytes_read:
        type: integer
      encoding:
        type: string
    post_execution:
      - "Assess if returned content is sufficient for the task"
      - "If file was truncated, re-read with explicit line range"
      - "When in doubt about completeness, re-read"

  - name: create_file
    description: >
      Create a new file with specified content.
      Use when generating new files that need permission controls.
      Do NOT use if file already exists — use update_file instead.
    risk: low
    consensus: any
    parallel_safe: true
    intent_required: true
    inputs:
      path:
        type: string
        required: true
      content:
        type: string
        required: true
      permissions:
        type: string
        required: false
        default: "644"
    outputs:
      success:
        type: boolean
      path:
        type: string
      bytes_written:
        type: integer
    post_execution:
      - "Verify file exists at path"
      - "Confirm permissions match requested value"

  - name: update_file
    description: >
      Modify existing file content (replace, append, prepend).
      Use when making targeted changes to existing files.
      Do NOT use for full file rewrites — use create_file with backup.
    risk: medium
    consensus: any
    parallel_safe: false
    intent_required: true
    inputs:
      path:
        type: string
        required: true
      operation:
        type: string
        required: true
        enum: [replace, append, prepend]
      pattern:
        type: string
        required: false
        description: "Required for replace operations"
      content:
        type: string
        required: true
      create_backup:
        type: boolean
        required: false
        default: true
    outputs:
      success:
        type: boolean
      backup_path:
        type: string
      bytes_written:
        type: integer
    post_execution:
      - "Verify file content reflects the change"
      - "If editing a config file, validate syntax"
      - "Confirm backup exists if create_backup was true"

  - name: delete_file
    description: >
      Permanently remove a file.
      Use ONLY when file is confirmed unnecessary.
      Do NOT use for temp cleanup — use move_file to temp directory.
    risk: high
    consensus: majority
    parallel_safe: false
    intent_required: true
    inputs:
      path:
        type: string
        required: true
        validation:
          - "MUST NOT match any protected_paths entry"
      create_backup:
        type: boolean
        required: false
        default: true
      force:
        type: boolean
        required: false
        default: false
    outputs:
      success:
        type: boolean
      backup_path:
        type: string
    post_execution:
      - "Verify file no longer exists"
      - "Confirm backup is accessible if created"
      - "Check for broken references (imports, configs) pointing to deleted file"

  - name: delete_directory
    description: >
      Remove directory and all contents.
      Use only for confirmed-unnecessary directories.
      Requires unanimous consensus due to blast radius.
    risk: critical
    consensus: unanimous
    parallel_safe: false
    intent_required: true
    inputs:
      path:
        type: string
        required: true
        validation:
          - "MUST NOT match any protected_paths entry"
      create_backup:
        type: boolean
        required: false
        default: true
      max_files:
        type: integer
        required: false
        default: 100
        description: "Safety cap — refuses if directory contains more files"
    outputs:
      success:
        type: boolean
      backup_path:
        type: string
      files_deleted:
        type: integer
    post_execution:
      - "Verify directory no longer exists"
      - "Confirm backup archive is valid"
      - "Check for broken references"

  - name: move_file
    description: >
      Move or rename a file.
      Use for reorganizing files or safe 'soft delete' to temp directory.
    risk: medium
    consensus: any
    parallel_safe: false
    intent_required: true
    inputs:
      source:
        type: string
        required: true
      destination:
        type: string
        required: true
      backup_destination:
        type: boolean
        required: false
        default: false
    outputs:
      success:
        type: boolean
      source:
        type: string
      destination:
        type: string
    post_execution:
      - "Verify file exists at destination"
      - "Verify file no longer exists at source"

  - name: copy_file
    description: >
      Duplicate a file or directory.
      Use for creating working copies or backups.
    risk: low
    consensus: any
    parallel_safe: true
    intent_required: true
    inputs:
      source:
        type: string
        required: true
      destination:
        type: string
        required: true
      recursive:
        type: boolean
        required: false
        default: false
      preserve_attributes:
        type: boolean
        required: false
        default: true
    outputs:
      success:
        type: boolean
      bytes_copied:
        type: integer
    post_execution:
      - "Verify destination exists"
      - "If preserve_attributes, spot-check permissions match source"

  - name: search_files
    description: >
      Find files matching name or content criteria.
      Use for discovery when file locations are unknown.
      Do NOT use for known patterns in known directories — use Glob or Grep.
    risk: low
    consensus: any
    parallel_safe: true
    intent_required: true
    inputs:
      path:
        type: string
        required: true
      pattern:
        type: string
        required: false
        description: "Glob pattern for filenames"
      content_match:
        type: string
        required: false
        description: "Regex for content matching"
      max_depth:
        type: integer
        required: false
        default: 10
    outputs:
      matches:
        type: array
        items:
          type: string
      match_count:
        type: integer
    post_execution:
      - "If zero matches, broaden search before concluding files don't exist"
      - "If matches exceed 50, narrow the search"

  - name: set_permissions
    description: >
      Change file permissions or ownership.
      Use only when permissions are explicitly wrong.
      Do NOT use speculatively.
    risk: high
    consensus: majority
    parallel_safe: true
    intent_required: true
    inputs:
      path:
        type: string
        required: true
        validation:
          - "MUST NOT match any protected_paths entry"
      permissions:
        type: string
        required: false
      owner:
        type: string
        required: false
      group:
        type: string
        required: false
      recursive:
        type: boolean
        required: false
        default: false
        validation:
          - "MUST NOT combine recursive=true with permissions='777'"
    outputs:
      success:
        type: boolean
      previous_permissions:
        type: string
    post_execution:
      - "Verify new permissions match requested value"
      - "If recursive, spot-check a few files"
      - "Confirm no protected paths were affected"

# ─────────────────────────────────────────────
# Verification
# ─────────────────────────────────────────────
verification:
  pre_conditions:
    - "Target path exists (for read/update/delete)"
    - "Parent directory exists (for create)"
    - "Sufficient disk space (for create/update/copy)"

  post_conditions:
    - "All outputs are populated"
    - "No protected paths were modified"
    - "Backups exist for all destructive operations"

  checkpoints:
    - trigger: "Before any destructive operation (delete, overwrite)"
      action: "Verify path is not protected and backup exists"
    - trigger: "Operating on path containing wildcards or globs"
      action: "List matches before proceeding"
    - trigger: "After multiple failed operations on same path"
      action: "Check permissions, disk space, and path validity"
    - trigger: "Before reporting completion"
      action: "Verify all outputs are populated and valid"

  completion_checklist:
    - "All requested operations executed successfully"
    - "No partial writes or incomplete operations"
    - "Backup paths returned for all destructive ops"
    - "Error field populated for any failures"

# ─────────────────────────────────────────────
# Error Handling
# ─────────────────────────────────────────────
error_handling:
  escalation:
    - error_class: recoverable
      description: "Permission denied, file locked"
      action: retry
      max_retries: 3
      fallback: "Report error with context, suggest manual resolution"

    - error_class: environment
      description: "Disk full, filesystem read-only"
      action: report
      max_retries: 0
      fallback: "Report immediately, do not attempt to fix environment"

    - error_class: permission
      description: "Protected path, insufficient privileges"
      action: escalate
      max_retries: 0
      fallback: "Escalate to user with path and required permissions"

    - error_class: repeated_failure
      description: "Same error after max_retries"
      action: stop
      fallback: "Stop, report what was attempted and what failed"

  self_correction:
    - "Destructive op without backup: immediately back up remaining state"
    - "Intent field omitted: acknowledge next turn, provide intent retroactively"
    - "Post-execution checks skipped: run them before next operation"
    - "Protected path check bypassed: halt all operations, verify no damage, report"

# ─────────────────────────────────────────────
# Inter-Agent Contracts
# ─────────────────────────────────────────────
contracts:
  provides:
    - name: file_content
      type: string
      consumers: [context-mapper, code-reviewer]
      description: "Raw file content for analysis"

    - name: backup_manifest
      type: object
      consumers: [multi-agent-supervisor]
      description: "List of backup paths created during execution"

    - name: search_results
      type: array
      consumers: [context-mapper, intent-author]
      description: "File paths matching search criteria"

  requires:
    - name: target_paths
      type: array
      provider: context-mapper
      description: "List of file paths identified during context mapping"

# ─────────────────────────────────────────────
# Constraints
# ─────────────────────────────────────────────
constraints:
  max_file_size_mb: 100
  max_concurrent_operations: 5
  max_files_per_directory_delete: 100
  backup_retention_days: 7

# ─────────────────────────────────────────────
# Protected Paths
# ─────────────────────────────────────────────
protected_paths:
  - /boot
  - /etc/fstab
  - /etc/passwd
  - /etc/shadow
  - /etc/sudoers
  - /usr/bin
  - /usr/lib
  - /usr/sbin
  - /lib
  - /lib64
  - /sbin
  - /bin
  - /proc
  - /sys
  - /dev
  - ~/.ssh/id_*
  - ~/.ssh/authorized_keys

# ─────────────────────────────────────────────
# Dependencies
# ─────────────────────────────────────────────
dependencies:
  python: [pathlib, shutil, os]
  system: [stat, find]
  skills: []
  config: []
